spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-value: org.h2.Driver



# -------------- uris ------------------
# enterprise service bus
esb:
  scheme: http
  host: 172.26.9.65
  users:
    port: 7171
    digitalizacion: /BsfPortalSucursalesDigitalizacion/
    uri:
      digitalizacion: ${esb.scheme}://${esb.host}:${esb.users.port}${esb.users.digitalizacion}
  wso2:
    port: 8288
    context-path: /wsBsfOperacionesSucursales/
    encrypt: ${esb.scheme}://${esb.host}:${esb.wso2.port}${esb.wso2.context-path}encrypt
    decrypt: ${esb.scheme}://${esb.host}:${esb.wso2.port}${esb.wso2.context-path}decrypt
# application server
as:
  scheme: http
  host: 172.26.9.65
  port: 9766
  context-path: /wsBsfOperacionesSucursales
  uri: ${esb.scheme}://${esb.host}:${esb.port}${esb.context-path}
  services:
      encryption:
        uri: ${esb.uri}/encrypt
      decryption:
        uri: ${esb.uri}/decrypt
# remittances back end services
remittances-back:
  scheme: http
  host: localhost
  port: 8090
  context-path: /bsf-national-remittances
  uri: ${remittances-back.scheme}://${remittances-back.host}:${remittances-back.port}${remittances-back.context-path}
  services:
    remittances:
      context-path: /remittances
      uri: ${remittances-back.uri}${remittances-back.services.remittances.context-path}
    payments:
      context-path: /payments
      uri: ${remittances-back.uri}${remittances-back.services.payments.context-path}
      cash:
        context-path: /cash
        uri: ${remittances-back.services.payments.uri}${remittances-back.services.payments.cash.context-path}
      accounts:
        context-path: /accounts
        uri: ${remittances-back.services.payments.uri}${remittances-back.services.payments.accounts.context-path}
        authorize:
         uri: ${remittances-back.services.payments.uri}/accounts/{account}/authorize
    products:
      context-path: /products
      uri: ${remittances-back.uri}${remittances-back.services.products.context-path}
    remittance-agencies:
      create:
        context-path: /remittance-agencies
        uri: ${remittances-back.uri}${remittances-back.services.remittance-agencies.create.context-path}
    reference-data:
      context-path: /reference-data
      uri: ${remittances-back.uri}${remittances-back.services.reference-data.context-path}
      states:
        context-path: /states
        uri: ${remittances-back.services.reference-data.uri}${remittances-back.services.reference-data.states.context-path}
      nationalities:
        uri: ${remittances-back.services.reference-data.uri}/nationalities
      identifications:
        uri: ${remittances-back.services.reference-data.uri}/identifications
      localities:
        uri: ${remittances-back.services.reference-data.uri}/localities/byPostalCode
      occupations:
        uri: ${remittances-back.services.reference-data.uri}/occupations
      countries:
        uri: ${remittances-back.services.reference-data.uri}/countries
      municipios:
        uri: ${remittances-back.services.reference-data.uri}/municipios




